version: "1"
rules:
  - base: main
    upstream: dsheeler:main
    mergeMethod: merge
    mergeUnstable: false
    assignees:
      - KyleGospo
    reviewers:
      - KyleGospo
    conflictReviewers:
      - KyleGospo
